---
title: "BZAN 6351 R Project"
author: "Team 5"
date: "2023-04-08"
output: html_document
---

```{r}
      #Data Preparation Step 1 Import data,check data using head () and summary statistics 
      #First we set the work directory to the file location of our athlete_events.csv file. This was done #using the ribbon. Session > Set working Directory > Choose Directory... Next we load the file using the "read.csv("athlete_events.csv) function". We then used the head() and summary() functions to gain a quick #overview of our data.
athletes <- read.csv("athlete_events.csv")
head(athletes)
summary(athletes)
```
```{r}
      #Data Preparation Step 2 - Convert the year variable to factor values
      #We then had to convert the year to a factor variable because the data is categorical.
athletes$Year <- as.factor(athletes$Year)
```
```{r}
      #Data Preparation Step 3 - Remove all NA values in Medal Column, and not others
      #Lastly, we removed the NA's from the Medal column to allow for easier data analysis using athletes 
athletes <- athletes[!(is.na(athletes$Medal)| athletes$Medal == ""),]
```
```{r}
      #Task 1 - Make a subset for Team United States in the dataset and assign it to USA.
      #Now that the data is easier to manipulate we can create a subset of USA through the subset() #function, and set the team to United States. 
USA <- subset(athletes, Team=="United States")
```
```{r}
      # Task 2 - Group by "sport" variable and Summarise the total medals in each sport and arrange them in descending order.
      #We created a variable USAsportsmedals by filtering the USA subset into separate sports using the "group_by" function. Once this data was filtered, we then were able to arrange the total medals by sport in descending order using the "arrange" and "desc" functions.
library(dplyr)
USAsportsmedals <- USA %>% group_by(Sport) 
USAsportsmedals %>% summarise(total_medals = sum(n())) %>% arrange(desc(total_medals))
USAsportsmedals
```
```{r}
      # Task 3 - Group by city, year and summarise the total medals won in each city 
#and raange them in descending order based on no. of medals
      #We created a variable USAcitymedals and performed group by operation on city, year on USA Dataset to #find and list the total medals won in descending order using arrange and desc functions.
USAcitymedals <- USA %>% group_by(City, Year)
USAcitymedals %>% summarise(total_medals = sum(n())) %>% arrange(desc(total_medals))
USAcitymedals

# US won the most medals in Sydney, followed by Atlanta and then Rio de Janeiro.

```
```{r}
      #Task 4 - create a variable "usa_swim" and make a subset for the sport swim.
      #To create the variable USA_swim we can access the USA subset we created earlier and filer by sport using another subset function, setting the sport to "Swimming"
usa_swim<-USA[USA$Sport=="Swimming",]
usa_swim

```
```{r}
      #Task 5 - From athletes dataset, calculate the medal tally per country 
#and sort them in descending order. 
      #We can calculate the medal tally by using the aggregate function. The aggregate function can group #the athletes dataset by the NOC variable and calculate the number of non NA's in the "medal" column for #each group. Now medal_tally will display two columns "NOC" and "Medal" or order the medals in descending #order we use the order() function and pass '-medal_tally$Medal' to order it in descending order
medaltally<-aggregate(Medal~NOC,data = athletes,FUN = function(x)length(na.omit(x)))
medaltally<-medaltally[order(-medaltally$Medal),] 
medaltally

#The United States received the highest number of gold medals.
# The US dominates is at the top at all the three positions.

```
```{r}
    #Task 6 - List the top 10 medal winning countries using the top_n() function
    #The table shown was generated by creating a variable "sorted_medal_tally" based on ordering the "medaltally" variable by "Medal" value and setting them in decreasing order using "order(medaltally$Medal, #decreasing = TRUE)" . the top_10_countries variable was then created from sorted_medal_tally to view the #top 10 values in descending order.
sorted_medal_tally <- medaltally[order(medaltally$Medal, decreasing = TRUE), ]
top_10_countries <- sorted_medal_tally[1:10, ]
top_10_countries

#The country that has won the most medals in the Olympics is USA, with 5637 medals. 
# In second place is the Soviet Union and in third place is Germany with 2165. 

```
```{r}
    #Task 7 - Plot the top 10 countries in a column chart with the title "Top 10 Medal Winning Countries"
    #we can use the descending ordered medal_tally variable created earlier. We can then import the top 10 #countries into a new data frame using the head() function on medal_tally. Finally we can plot the graph #using the barplot() function to create a column chart. Inside the barplot function, we can pass the #arguments x.lab and y.lab to label the axis. Furthermore, we can pass the main argument for the Title #name. The top_countries$Medal is what will be plotted as bars, and top_countries$Country specifies the #labels for each bar (a vector of country names)
library(ggplot2)
country_medals <- athletes %>% group_by(NOC, Medal) %>% summarise(count = n()) %>% ungroup()
country_count <- country_medals %>% filter(!is.na(Medal)) %>% group_by(NOC) %>% summarise(total_medals = sum(count)) %>%  ungroup()
best_10 <- country_count %>% arrange(desc(total_medals)) %>% 
slice(1:10)
ggplot(best_10, aes(x = NOC, y = total_medals, fill = NOC)) +
geom_col() + 
labs(title = "Top 10 Medal Winning Countries")

#The top 10 countries are USA,Australia, Canada, Great Britain, Germany, France, Italy, Russia,
#Sweden and URS.
#The United States has won the most medals than the other countries.
#No other country has won at least half of what US has won.
#The least of the top 10 countries by medals were won by Russia.

```
```{r}
      #Task 8 - Calculate the medal tally of countries per year and assign to "medal_countries"
      #We created a variable medal_countries to find the medal tally by using group_by function on team and #year and then summarized the data.
medal_countries <- athletes %>% group_by(Team,Year) %>% summarise(count=sum(n()))
medal_countries

# It can be seen that the US won the highest number of medals in 1992 with 936 compared to all other #countries.
# It was also in second place with the highest number of medals in 1988 with 886 medals. 

```
```{r}
    #Task 9 - From the athletes dataset, now Group by team and medal, 
# and then summarize the count of medals, display them in descending order.
    #We goruped the full data set by Team and Medal using the "group_by" function. Once these were grouped #we manipulated the data to show teams with the amount of medals they had won in decending order by using #arrange(Team,desc(count)).
athletes_team_medal <- athletes %>% group_by(Team,Medal) %>% summarise(count = n()) %>% arrange(Team,desc(count)) 
athletes_team_medal

```
```{r}
    #Task 10 - For team “United States”, “France”, “Germany”, “Great Britain” show their medal count by the #number of gold, silver, and bronze. Plot it too displaying the Teams and the medal counts 
    #First we must be sure that ggplot2 package is installed in R by using the library(ggplot2) function. #We can assign the countries to a dataset by creating a factor of the desired countries (United States, #France, Germany, and Great Britain) using the factor function c().  Now we can create a subset of these #countries using the subset() function in the athlete's dataset and filter by the respective countries. You #can then assign a dataset of medal_count where you group by the team and count the meals won using the #summarize() function. Lastly, you can plot the bar graph using the ggplot() function. Inside the ggplot #function, you can pass the arguments for the x and y axis, Team and medal_count respectively. Additionally #you can pass the argument for color and labels for the x, y axis, and title of the graph. The graph shows #America, Germany, Great Britain, and France from highest to lowest of medal counts.

Teams.4 <- c("United States","France","Germany","Great Britain")
Teams.4.new <- athletes %>% filter(Team %in% Teams.4)
medal_count <- Teams.4.new %>%group_by(Team, Medal) %>% summarise(count = n())
library(ggplot2)
ggplot(medal_count, aes(x = Team, y = count, fill = Medal)) +
geom_bar(stat = "identity") + 
ggtitle("Medal Counts by Team") + 
labs(x = "Team", y = "medal_count") + 
scale_fill_manual(values = c("#FFD700", "#C0C0C0", "#CD7F32"),
labels = c("Gold", "Silver", "Bronze"))

```
```{r}
    #Task 11 - Show the medal count of gold by team, display them in the descending order.
    #we created a variable medal_count_gold to find the gold medal count of each team using group_by #function on Team and Medal on the athlete data, summarised then and arranged them in descdending order #based on count.
medal_count_Gold<- athletes %>% group_by(Team,Medal) %>% filter(Medal== "Gold") %>% summarise(count=n()) %>% arrange(desc(count)) 
medal_count_Gold
#The Leander Club-1 and Vesper Boat Club have the highest number of Gold Medala.

```
```{r}
    #Task 12 - Show the medal count of Silver by team, display them in the descending order.
    #Using the "filter" function we were able to only show the count of silver medals by setting #"Medal=="Silver"" and then used the "arrange" function to list them in descending order. This list was #given a variable name of medal_count_Silver.
medal_count_Silver<- athletes %>% group_by(Team,Medal) %>% filter(Medal== "Silver") %>% summarise(count=n()) %>% arrange(desc(count)) 
medal_count_Silver

# Phalainis ton Thorichtou "Hydra"-2 have the highest number of Silver medals.

```
```{r}
    #Task 13 - Show the medal count of Bronze by team, display them in the descending order.
    #Using the "filter" function we were able to only show the count of bronze medals by setting "Medal=="Bronze"" and then used the "arrange" function to list them in descending order. This list was #given a variable name of medal_count_Bronze.
medal_count_Bronze<- athletes %>% group_by(Team,Medal) %>% filter(Medal== "Bronze") %>% summarise(count=n()) %>% arrange(desc(count)) 
medal_count_Bronze

# Marinai della nave da guerra "Varese" had the highest number of bronze medals.

```
```{r}
    #Task 14. Plot the total medal count of the following countries: “United States”, “France”, “Germany”,“Great Britain.”

  #14 First we created a dataset of the countries by factoring the countries United States, France, #Germany, and Great Britain. We then created a subset of that dataset using the subset function, where we #only got the Teams from those countries. Next, we created a medal_count which is grouped by the Team #(country). Finally we can group create the column chart using the ggplot() function. This function was #passed the arguments, x = Team, Total_medals and y as total_medals. Finally the color and axis labels.

Teams.4 <- c("United States", "France", "Germany", "Great Britain")
country_data <- subset(athletes, Team %in% Teams.4 )
medal_count <- country_data %>% 
group_by(Team) %>% 
summarize(Total_Medals = n())
ggplot(medal_count, aes(x = reorder(Team, Total_Medals), y = Total_Medals)) +
geom_col(fill = "steelblue") +
labs(title = "Total Medal Count of Selected Countries", x = "Country", y = "Total Medals")

```
```{r}
  #Task 15 For “United States”, “Russia”, “Germany”, “France”, and “China” compare the medal tally for       #summer and winter games and plot and display them.

#First we created a factor of the countries United States, Russia, Germany, and France. Next, we calculated #the medals grouped by team and Season. We created a factor of the countries United States, Russia, #Germany, and France. Next, we created a subset where only the data points for the athletes in those #countries (Team) were accounted for. Next, we calculated the medals grouped by team and Season. Finally, #we can plot the graph using the ggplot() function. We passed the arguments, team, and total_medals for x #and y respectively. We separated the medal count by Season. lastly, we labeled the axis and title. and #filled the columns based on the season for easy differentiation.

countries <- c("United States", "Russia", "Germany", "France", "China") 
filtered_athletes <- subset(athletes, Team %in% countries) 
medals <- filtered_athletes %>% group_by(Team, Season) %>% summarise(total_medals = sum(!is.na(Medal)))

ggplot(medals, aes(x = Team, y = total_medals, fill = Season)) + 
geom_bar(stat = "identity", position = position_dodge()) + 
labs(x = "Country", y = "Total Medals", title = "Medal Tally Comparison for Summer and Winter Games") + scale_fill_manual(values = c("red","#87CEEB"), labels = c("Summer", "Winter"))

#The United States has won the most medals in winter and summer compared to Great Britain, Russia, France, #and China. 
#China won the least amount of medals in the winter and summer games compared to the other countries.
#Countries won more medals in the summer than they did in winter.


```
```{r}
    #Task 16 Calculate Medals won by women in the year 2016.
 #16 The data from "athletes" was filtered to display the medals won by only women in 2016 by using the "filter" function and setting Year==2016 and the sex=="F". The "count" function was then used to display the medals won according to said filters.

medals_won_by_women <- athletes %>% filter(Year == 2016 & Sex == "F") %>% count(Medal)
medals_won_by_women

# Female athletes won more medals at the 2016 Olympics, than compared to previous years.
# The medals won are almost at the same mark across all the three positions i.e., Gold, Silver and Bronze. 

```

